os: linux
language: python
python:
  - 3.5
  - 3.6

install: pip install -U tox-travis codecov
script: tox
after_success: codecov

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      python: 3.6
      script: tox -e lint

    - stage: test
      python: 3.7
      dist: xenial

    - stage: test
      python: 3.8
      dist: xenial

    - stage: deploy
      python: 3.6
      script: tox --notest
      name: "Release to PyPI"
      deploy:
        edge: true
        provider: pypi
        distributions: sdist bdist_wheel
        username: micahjsmith
        password:
          secure: "mLibqiLrgLb1esoPJlPsYjWKzv41Doe/z27jnC8ZTKq+nEd0gTLFPEDsqum0PaKs0lrqNoeyRQBCn/y24PrSWWua4CygcrvWW/k18tewpogNACkgS2oG0SY+/mqGpIyT4G6KV+jlweAxX7BhTg83frvc5HwRnT3HyHFYOH9Z5zpU5lX4fdBVLzQZJgkGeNcA7rlYDG31aHmiWdf5UQrVfSyJk/rabfKnENGbUHibkCDkVOOlGKUFXzn0sZfD+5Hmezvv+WlpE4172hNCkJIhNu10jqm4SzdRwZqPt3VimLBWVFVghike0MLnRxx4ELM4gtuLgvtPa4PcwJyjnz184LxbYALxEQ97sUuJtGOvB8P6MPyymNNzKCheAtUvdftnfsuLzCBcz0AhdNaoqbgeIDVl0BpowBXAVDQk/I8xyFiAIS5CE5HE13FCiTwxEeToC1fKYQfm7k1s6cUBelSK5PtYcLTJ2u6GFs+hFX2bBBWI8+OaQUntj7w8wzdKYYdkBi/cBk+l99+qYbDeugtNtVVzwX9BHHRqhFemcNCwxOUFWf5ABlxg0jhgC55eEw5igpqrCjhVpzYlP8VM3zsZDCfI4HNMvoFxIh5Th70+fzM/tuaiC2naC7AEkcB6pgJP3fuXy5fxI+B0a94FetfhEGw1JcQwzZeEfUwe9nhLM9I="
        on:
          tags: true
          repo: HDI-Project/ballet

    - stage: deploy
      python: 3.6
      script: tox -e docs
      name: "Build docs"
      deploy:
        edge: true
        provider: pages
        cleanup: false
        token: "$GITHUB_TOKEN"
        keep_history: true
        local_dir: docs/_build/html
        target_branch: gh-pages
        on:
          branch: master

notifications:
  email:
    on_success: never
    on_failure: change
